### ISSUE TITLE
double check huggingface backend, apparently does not get passed temperature parameter correctly

### ISSUE THREAD

**Issue by davidschlangen** [clp-research/clemcore#15]
(As reported by Jonathan) - backend complains about temperature parameter. The other backends do get (or at least are supposed) to get this parameter when called, so need to go back and check this.

**Comment by Gnurro** [comment]
In theory the current code should work as intended - I will test this along with testing the local models and report back if there's an actual issue.
This may just be due to the `transformers` `generate` method being rather bloated and allowing too many potentially conflicting arguments to be passed. In that case, simply turning off the `transformers` warnings would 'solve' the issue. See https://github.com/huggingface/transformers/issues/22405#issuecomment-1485527953 : 
> We are aware that our `.generate()` has too many options and too little checks/examples, we are working on it 🤗

**Comment by Gnurro** [comment]
Temperature is set properly - it's logged now, showing that it's set to 0.0 as intended.
