### ISSUE TITLE
allow users to provide model identifiers as arguments (instead of options)

### ISSUE THREAD

**Issue by phisad** [clp-research/clemcore#34]
**Problem**
When running the benchmark for a 2-player game, then users have to specify both side, even when they are the same:
```
python3 scripts/cli.py -m fsc-vicuna-7b-v1.5--fsc-vicuna-7b-v1.5 run taboo
```
This is unnecessary lengthy and prone for errors.
**Solution A**
To simplify here and we can assume that the model is playing "with itself" per default, so that only the following has to be called:
```
python3 scripts/cli.py -m fsc-vicuna-7b-v1.5 run taboo
```
This automatically aligns with single-player configurations. Furthermore we allow to specify a specific model for the other player in 2-player games:
```
python3 scripts/cli.py -m fsc-vicuna-7b-v1.5 --other llama2 run taboo
```
**Problem with Solution A**
Now this does **not** generalize possible games with more than 2 players. And the framework code needs to know how many player a game requires.

**Solution B**
Thus an even better approach would be to simply take the model names as arguments and let the games decide what they wanna do with it (the 2-player games could by default use the only provided backend for both players or raise an exception when a wrong number of players is provided). 

Such a call would look like:
```
python3 scripts/cli.py run taboo model1[,model2,model3...]
```
The results folder name will be simply a "--" concatenation of the provided model names.

**Todos**
- adjust cli
- adjust result folder name production
- adjust all games and how they handle the provided players (e.g. throw an exception for privateshared with more than 2 players)
- adjust the pipeline scripts (that for now run single games and the models)

**Comment by phisad** [comment]
What do you think @davidschlangen @Gnurro ? Solution B looks very straight-forward but would need to adjust also all game code a bit (when given only a single model argument, then still this for both player sides). A less impactful strategy could be to first change only the framework code (and not the games), so that users still need to specify model1 and model2 (even when the same).

**Comment by davidschlangen** [comment]
I like option B. But why do the games need to change? Can `cli.py` not translate a call with only one model name into an internal call of the game with that model being player A and B?

**Comment by Gnurro** [comment]
There already is parsing and other handling of the model selection string, since the results have the temperature added - and with the upcoming model registry, the model selection can potentially use a different model name than the results directories and others.

In general I like either, as it's an improvement over how it worked so far.
For B: Good separator would be / (or ;), since those never appear in the specific model names on Huggingface, while dashes and periods are pretty common.

I think that making the CLI arguments more explicit/less reliant on order would be helpful as well, even if that makes them more verbose: `python3 scripts/cli.py run --game taboo --models model1[,model2,model3...]` or similar.
Further model options/settings should also be possible to be passed, preferably for each model. Allowing passing this as structured data like JSON would also make it robust, maybe even allowing to make run configurations as structured data down the line that can be loaded from files.

**Comment by phisad** [comment]
> Can `cli.py` not translate a call with only one model name into an internal call of the game with that model being player A and B?

The idea is that clem (as the framework) should not know about what number of players the games (as framework users) need. But I hacked this a bit knowing that we only have 2-player games for now and provided the games with a "is_single_player" method to distinguish between 1 or 2 players. Theoretically, there could be also 3-players and more... letting the games decide if they are happy with the number of player given at setup will make things clearer and easier, I guess.

**Comment by Gnurro** [comment]
> Can cli.py not translate a call with only one model name into an internal call of the game with that model being player A and B?

I don't know about cli.py, but `run.sh` does already take a single model name for singleplayer games.
