### ISSUE TITLE
`scripts/cli.py ls` broken?

### ISSUE THREAD

**Issue by davidschlangen** [clp-research/clemcore#4]
When doing the following:
`(clembench) clembench % python scripts/cli.py ls`

I get an error:
```
No module named 'torch'
Cannot load 'backends.huggingface_local_api'. Please make sure that the file exists.
Loaded backends: anthropic,openai,alephalpha
2023-10-31 13:26:18,827 - benchmark.run - INFO - Listing benchmark games:
Traceback (most recent call last):
  File "/Users/das/mst22_synced/work/local/Gits/2023/clembench/scripts/cli.py", line 74, in <module>
    main(args)
  File "/Users/das/mst22_synced/work/local/Gits/2023/clembench/scripts/cli.py", line 33, in main
    benchmark.list_games()
  File "/Users/das/mst22_synced/work/local/Gits/2023/clembench/clemgame/benchmark.py", line 15, in list_games
    games_list = load_benchmarks(dialog_pair=None, do_setup=False)
TypeError: load_benchmarks() got an unexpected keyword argument 'dialog_pair'
Exit 1
```

Assuming that isn't because I haven't installed torch in this environment (and it shouldn't be; otherwise that would have to be part of the requirements), the problem seems to be somewhere inside of `load_benchmarks()`.

**Comment by Gnurro** [comment]
```
No module named 'torch'
Cannot load 'backends.huggingface_local_api'. Please make sure that the file exists.
```
This is due to `backends/__init__.py` importing all `_api.py` files, including the HF backend, which requires torch. The HF requirements are seperated into `requirements_hf.txt`.
This can be solved by either making seperate branches supporting different backends or by adding the HF requirements/setup to the base setup.
The error message `Please make sure that the file exists.` is also misleading here, as the file does exist, but the error occurs because the file does not import properly due to the missing torch requirement.

Since I'm not yet familiar with the code beyond the backends, I don't know if and how that might lead to downstream issues.

**Comment by davidschlangen** [comment]
Yeah no, I don't think that is the issue. (The main error doesn't go away when torch is installed.)

**Comment by Gnurro** [comment]
https://github.com/clp-research/clembench/blob/13d68fb6fb972281a59731b8a2f25e7b20ad74b7/clemgame/benchmark.py#L15
https://github.com/clp-research/clembench/blob/13d68fb6fb972281a59731b8a2f25e7b20ad74b7/clemgame/clemgame.py#L818
`load_benchmarks()` simply does not take that argument. I'd remove `dialog_pair=None` from the call, but would ask @phisad what the intention behind passsing it is.
